export const availableDocs = [
  { urlName: 'store-components', formattedName: 'Store Components' },
  { urlName: 'store-header', formattedName: 'Store Header' },
  { urlName: 'order-placed', formattedName: 'Order Placed' },
  { urlName: 'store-footer', formattedName: 'Store Footer' },
  { urlName: 'shelf', formattedName: 'Shelf' },
  { urlName: 'carousel', formattedName: 'Carousel' },
  { urlName: 'menu', formattedName: 'Menu' },
  { urlName: 'minicart', formattedName: 'Minicart' },
  { urlName: 'telemarketing', formattedName: 'Telemarketing' },
  { urlName: 'login', formattedName: 'Login' },
  { urlName: 'category-menu', formattedName: 'Category Menu' },
  { urlName: 'breadcrumb', formattedName: 'Breadcrumb' },
  { urlName: 'search-result', formattedName: 'Search Result' },
  { urlName: 'product-details', formattedName: 'Product Details' },
  {
    urlName: 'address-locator',
    formattedName: 'Address Locator',
  },
  { urlName: 'flex-layout', formattedName: 'Flex Layout' },
  { urlName: 'my-account', formattedName: 'My Account' },
  { urlName: 'my-account-commons', formattedName: 'My Account Commons' },
  { urlName: 'product-customizer', formattedName: 'Product Customizer' },
  { urlName: 'product-kit', formattedName: 'Product Kit' },
  { urlName: 'product-summary', formattedName: 'Product Summary' },
  { urlName: 'store-icons', formattedName: 'Store Icons' },
  { urlName: 'rich-text', formattedName: 'Rich Text' },
  { urlName: 'wishlist', formattedName: 'Wishlist' },
  { urlName: 'facebook-pixel', formattedName: 'Facebook Pixel' },
  { urlName: 'google-adwords', formattedName: 'Google Adwords' },
  { urlName: 'google-tag-manager', formattedName: 'Google Tag Manager' },
]
