export const availableDocs = [
  { urlName: 'vtex.store-components', formattedName: 'Store Components' },
  { urlName: 'vtex.release-notes', formattedName: 'Release Notes' },
  { urlName: 'vtex.store-header', formattedName: 'Store Header' },
  { urlName: 'vtex.order-placed', formattedName: 'Order Placed' },
  { urlName: 'vtex.store-footer', formattedName: 'Store Footer' },
  { urlName: 'vtex.shelf', formattedName: 'Shelf' },
  { urlName: 'vtex.carousel', formattedName: 'Carousel' },
  { urlName: 'vtex.menu', formattedName: 'Menu' },
  { urlName: 'vtex.minicart', formattedName: 'Minicart' },
  { urlName: 'vtex.telemarketing', formattedName: 'Telemarketing' },
  { urlName: 'vtex.login', formattedName: 'Login' },
  { urlName: 'vtex.category-menu', formattedName: 'Category Menu' },
  { urlName: 'vtex.breadcrumb', formattedName: 'Breadcrumb' },
  { urlName: 'vtex.search-result', formattedName: 'Search Result' },
  { urlName: 'vtex.product-details', formattedName: 'Product Details' },
  {
    urlName: 'vtex.address-locator',
    formattedName: 'Address Locator',
  },
  { urlName: 'vtex.flex-layout', formattedName: 'Flex Layout' },
  { urlName: 'vtex.my-account', formattedName: 'My Account' },
  { urlName: 'vtex.my-account-commons', formattedName: 'My Account Commons' },
  { urlName: 'vtex.product-customizer', formattedName: 'Product Customizer' },
  { urlName: 'vtex.product-kit', formattedName: 'Product Kit' },
  { urlName: 'vtex.product-summary', formattedName: 'Product Summary' },
  { urlName: 'vtex.store-icons', formattedName: 'Store Icons' },
  { urlName: 'vtex.rich-text', formattedName: 'Rich Text' },
  { urlName: 'vtex.wishlist', formattedName: 'Wishlist' },
]
